# Generated by Django 5.0.6 on 2024-05-30 17:57

import songbird.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbird', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to=songbird.models.song_file_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=songbird.models.user_profile_image_path),
        ),
    ]
