# Generated by Django 5.0.6 on 2024-05-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbird', '0002_alter_song_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
