# Generated by Django 5.0.6 on 2024-05-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbird', '0006_alter_song_play_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='play_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
