# Generated by Django 5.0.6 on 2024-06-02 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbird', '0008_alter_song_play_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
