# Generated by Django 5.0.6 on 2024-06-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbird', '0009_song_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_songs',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='songbird.song'),
        ),
    ]
