# Generated by Django 5.0.6 on 2024-06-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbird', '0011_playlist_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
