# Generated by Django 5.0.6 on 2024-06-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbird', '0013_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
