# Generated by Django 5.0.6 on 2024-06-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songbird', '0014_playlist_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
